<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Tour;
use Illuminate\Support\Str;

class CulinaryTourSeeder extends Seeder
{
    public function run()
    {
        $culinaryTours = [
            [
                'name' => 'Gudeg Yu Djum Pusat',
                'description' => 'Gudeg legendaris Yogyakarta dengan cita rasa autentik dan bumbu rahasia turun temurun.',
                'location' => 'Jl. Wijilan No.167, Kota Yogyakarta',
                'address' => 'Jl. Wijilan No.167, Panembahan, Kraton, Yogyakarta City',
                'latitude' => -7.8056,
                'longitude' => 110.3644,
                'price' => 15000,
                'duration' => '1-2 jam',
                'includes' => 'Gudeg komplit, Nasi, Teh manis',
                'excludes' => 'Minuman tambahan, Transportasi, Oleh-oleh',
                'itinerary' => 'Datang: Menikmati gudeg hangat. Selesai: Beli oleh-oleh gudeg kaleng.',
                'max_participants' => 20,
                'difficulty_level' => 'easy',
            ],
            [
                'name' => 'Bakpia Pathok 25',
                'description' => 'Bakpia original Yogyakarta dengan berbagai varian rasa dan kualitas terjamin sejak 1948.',
                'location' => 'Jl. AIP II KS Tubun, Pathok, Kota Yogyakarta',
                'address' => 'Jl. KS Tubun No.3, Sosromenduran, Gedongtengen, Yogyakarta City',
                'latitude' => -7.7944,
                'longitude' => 110.3656,
                'price' => 25000,
                'duration' => '1 jam',
                'includes' => 'Tasting bakpia, Teh/kopi, Penjelasan proses pembuatan',
                'excludes' => 'Pembelian bakpia, Transportasi, Makanan lain',
                'itinerary' => 'Datang: Tasting berbagai rasa bakpia. Selesai: Belanja bakpia untuk oleh-oleh.',
                'max_participants' => 15,
                'difficulty_level' => 'easy',
            ],
            [
                'name' => 'Angkringan Lik Man',
                'description' => 'Angkringan legendaris dekat Stasiun Tugu dengan suasana khas Yogyakarta dan menu tradisional.',
                'location' => 'Dekat Stasiun Tugu, Jl. Wongsodirjan, Kota Yogyakarta',
                'address' => 'Jl. Wongsodirjan, Pringgokusuman, Gedongtengen, Yogyakarta City',
                'latitude' => -7.7889,
                'longitude' => 110.3639,
                'price' => 20000,
                'duration' => '2-3 jam',
                'includes' => 'Nasi kucing, Sate usus, Wedang jahe, Suasana angkringan',
                'excludes' => 'Makanan tambahan, Transportasi, Minuman lain',
                'itinerary' => 'Malam: Datang ke angkringan. Malam: Menikmati makanan dan ngobrol. Selesai: Pulang kenyang.',
                'max_participants' => 25,
                'difficulty_level' => 'easy',
            ],
            [
                'name' => 'Sate Klathak Pak Pong',
                'description' => 'Sate kambing khas Bantul yang dipanggang dengan arang dan bumbu kacang yang gurih.',
                'location' => 'Jl. Imogiri Timur KM 10, Jejeran, Bantul',
                'address' => 'Jl. Imogiri Timur KM 10, Jejeran, Wonokromo, Bantul Regency',
                'latitude' => -7.8833,
                'longitude' => 110.3833,
                'price' => 35000,
                'duration' => '1-2 jam',
                'includes' => 'Sate klathak, Nasi, Sambal, Teh manis',
                'excludes' => 'Minuman tambahan, Transportasi, Makanan lain',
                'itinerary' => 'Datang: Pesan sate klathak. Tunggu: Melihat proses pembakaran. Makan: Menikmati sate hangat.',
                'max_participants' => 30,
                'difficulty_level' => 'easy',
            ],
            [
                'name' => 'Mie Ayam Tumini',
                'description' => 'Mie ayam legendaris dengan kuah kaldu yang gurih dan topping ayam yang melimpah.',
                'location' => 'Jl. Imogiri Timur No.187, Umbulharjo, Kota Yogyakarta',
                'address' => 'Jl. Imogiri Timur No.187, Giwangan, Umbulharjo, Yogyakarta City',
                'latitude' => -7.8333,
                'longitude' => 110.3833,
                'price' => 18000,
                'duration' => '1 jam',
                'includes' => 'Mie ayam komplit, Pangsit, Teh manis',
                'excludes' => 'Minuman tambahan, Transportasi, Makanan lain',
                'itinerary' => 'Datang: Pesan mie ayam. Tunggu: Melihat proses pembuatan. Makan: Menikmati mie ayam hangat.',
                'max_participants' => 20,
                'difficulty_level' => 'easy',
            ],
            [
                'name' => 'Oseng Mercon Bu Narti',
                'description' => 'Oseng-oseng pedas level tinggi yang menantang lidah dengan cita rasa yang nagih.',
                'location' => 'Jl. KH Ahmad Dahlan, Kota Yogyakarta',
                'address' => 'Jl. KH Ahmad Dahlan, Ngampilan, Yogyakarta City',
                'latitude' => -7.8000,
                'longitude' => 110.3667,
                'price' => 22000,
                'duration' => '1-2 jam',
                'includes' => 'Oseng mercon, Nasi, Es teh manis, Susu untuk meredakan pedas',
                'excludes' => 'Makanan tambahan, Transportasi, Minuman lain',
                'itinerary' => 'Datang: Pesan oseng mercon. Makan: Tantangan pedas dimulai. Selesai: Minum susu untuk meredakan.',
                'max_participants' => 15,
                'difficulty_level' => 'moderate',
            ],
            [
                'name' => 'Gudeg Pawon',
                'description' => 'Gudeg dengan cita rasa manis khas Yogyakarta yang dimasak dengan kayu bakar tradisional.',
                'location' => 'Jl. Janturan No.36, Umbulharjo, Kota Yogyakarta',
                'address' => 'Jl. Janturan No.36, Warungboto, Umbulharjo, Yogyakarta City',
                'latitude' => -7.8167,
                'longitude' => 110.3833,
                'price' => 20000,
                'duration' => '1-2 jam',
                'includes' => 'Gudeg komplit, Nasi, Sambal krecek, Teh manis',
                'excludes' => 'Minuman tambahan, Transportasi, Oleh-oleh',
                'itinerary' => 'Datang: Pesan gudeg pawon. Makan: Menikmati gudeg hangat. Selesai: Beli gudeg untuk dibawa pulang.',
                'max_participants' => 25,
                'difficulty_level' => 'easy',
            ],
            [
                'name' => 'Mangut Lele Mbah Marto',
                'description' => 'Mangut lele dengan kuah santan pedas yang khas dan lele segar dari kolam sendiri.',
                'location' => 'Ngireng-ireng, Sewon, Kab. Bantul',
                'address' => 'Ngireng-ireng, Panggungharjo, Sewon, Bantul Regency',
                'latitude' => -7.8500,
                'longitude' => 110.3500,
                'price' => 28000,
                'duration' => '1-2 jam',
                'includes' => 'Mangut lele, Nasi, Lalapan, Es teh',
                'excludes' => 'Ikan tambahan, Transportasi, Minuman lain',
                'itinerary' => 'Datang: Pilih lele segar. Tunggu: Proses memasak mangut. Makan: Menikmati mangut lele hangat.',
                'max_participants' => 20,
                'difficulty_level' => 'easy',
            ],
            [
                'name' => 'Jejamuran Resto',
                'description' => 'Restoran khusus jamur dengan berbagai olahan jamur yang unik dan sehat.',
                'location' => 'Jl. Pendowoharjo, Niron, Sleman',
                'address' => 'Jl. Pendowoharjo, Niron, Srandakan, Bantul Regency',
                'latitude' => -7.9167,
                'longitude' => 110.2833,
                'price' => 45000,
                'duration' => '2-3 jam',
                'includes' => 'Menu jamur pilihan, Nasi, Minuman, Tur kebun jamur',
                'excludes' => 'Menu premium, Transportasi, Oleh-oleh jamur',
                'itinerary' => 'Datang: Tur kebun jamur. Makan: Menikmati berbagai olahan jamur. Selesai: Belanja jamur segar.',
                'max_participants' => 30,
                'difficulty_level' => 'easy',
            ],
            [
                'name' => 'Wedang Ronde Mbah Payem',
                'description' => 'Wedang ronde legendaris di Alun-alun Kidul dengan ronde isi kacang yang hangat.',
                'location' => 'Alun-alun Kidul, Kota Yogyakarta',
                'address' => 'Alun-alun Kidul, Patehan, Kraton, Yogyakarta City',
                'latitude' => -7.8111,
                'longitude' => 110.3639,
                'price' => 12000,
                'duration' => '1 jam',
                'includes' => 'Wedang ronde, Kacang rebus, Suasana alun-alun',
                'excludes' => 'Makanan tambahan, Transportasi, Minuman lain',
                'itinerary' => 'Malam: Datang ke alun-alun. Malam: Menikmati wedang ronde hangat. Selesai: Jalan-jalan di alun-alun.',
                'max_participants' => 15,
                'difficulty_level' => 'easy',
            ],
            [
                'name' => 'Ayam Goreng Mbah Cemplung',
                'description' => 'Ayam goreng dengan bumbu meresap dan sambal yang pedas, disajikan dengan lalapan segar.',
                'location' => 'Jalan Parangtritis KM 10, Bantul',
                'address' => 'Jl. Parangtritis KM 10, Sewon, Bantul Regency',
                'latitude' => -7.8667,
                'longitude' => 110.3500,
                'price' => 32000,
                'duration' => '1-2 jam',
                'includes' => 'Ayam goreng, Nasi, Lalapan, Sambal, Es teh',
                'excludes' => 'Ayam tambahan, Transportasi, Minuman lain',
                'itinerary' => 'Datang: Pesan ayam goreng. Tunggu: Proses menggoreng ayam. Makan: Menikmati ayam goreng hangat.',
                'max_participants' => 25,
                'difficulty_level' => 'easy',
            ],
            [
                'name' => 'Lumpia Samijaya',
                'description' => 'Lumpia basah dan goreng khas Yogyakarta di kawasan Malioboro dengan isian yang melimpah.',
                'location' => 'Malioboro, Kota Yogyakarta',
                'address' => 'Jl. Malioboro, Sosromenduran, Gedongtengen, Yogyakarta City',
                'latitude' => -7.7944,
                'longitude' => 110.3656,
                'price' => 18000,
                'duration' => '1 jam',
                'includes' => 'Lumpia basah dan goreng, Sambal, Teh manis',
                'excludes' => 'Lumpia tambahan, Transportasi, Minuman lain',
                'itinerary' => 'Datang: Pesan lumpia. Makan: Menikmati lumpia hangat. Selesai: Jalan-jalan di Malioboro.',
                'max_participants' => 20,
                'difficulty_level' => 'easy',
            ],
            [
                'name' => 'Soto Kadipiro',
                'description' => 'Soto ayam dengan kuah bening yang segar dan daging ayam yang empuk.',
                'location' => 'Jl. Wates KM 4,5, Yogyakarta',
                'address' => 'Jl. Wates KM 4,5, Gamping, Sleman Regency',
                'latitude' => -7.7833,
                'longitude' => 110.3167,
                'price' => 16000,
                'duration' => '1 jam',
                'includes' => 'Soto ayam, Nasi, Kerupuk, Teh manis',
                'excludes' => 'Soto tambahan, Transportasi, Minuman lain',
                'itinerary' => 'Datang: Pesan soto ayam. Makan: Menikmati soto hangat. Selesai: Minum teh manis.',
                'max_participants' => 20,
                'difficulty_level' => 'easy',
            ],
            [
                'name' => 'Bakmi Jawa Mbah Mo',
                'description' => 'Bakmi Jawa dengan bumbu khas dan topping yang melimpah, disajikan dengan kerupuk.',
                'location' => 'Code, Bantul',
                'address' => 'Code, Bantul Regency',
                'latitude' => -7.8833,
                'longitude' => 110.3333,
                'price' => 14000,
                'duration' => '1 jam',
                'includes' => 'Bakmi Jawa, Kerupuk, Teh manis',
                'excludes' => 'Bakmi tambahan, Transportasi, Minuman lain',
                'itinerary' => 'Datang: Pesan bakmi Jawa. Makan: Menikmati bakmi hangat. Selesai: Minum teh manis.',
                'max_participants' => 15,
                'difficulty_level' => 'easy',
            ],
            [
                'name' => 'Es Buah PK',
                'description' => 'Es buah segar dengan berbagai macam buah tropis dan sirup yang manis.',
                'location' => 'Jl. Pakuningratan, Jetis',
                'address' => 'Jl. Pakuningratan, Cokrodiningratan, Jetis, Yogyakarta City',
                'latitude' => -7.7833,
                'longitude' => 110.3500,
                'price' => 10000,
                'duration' => '30 menit',
                'includes' => 'Es buah komplit, Sirup, Es serut',
                'excludes' => 'Buah tambahan, Transportasi, Minuman lain',
                'itinerary' => 'Datang: Pesan es buah. Minum: Menikmati es buah segar. Selesai: Merasa segar kembali.',
                'max_participants' => 10,
                'difficulty_level' => 'easy',
            ],
        ];

        foreach ($culinaryTours as $tour) {
            Tour::create([
                'name' => $tour['name'],
                'slug' => Str::slug($tour['name']),
                'category' => 'culinary',
                'description' => $tour['description'],
                'price' => $tour['price'],
                'duration' => $tour['duration'],
                'location' => $tour['location'],
                'address' => $tour['address'],
                'latitude' => $tour['latitude'],
                'longitude' => $tour['longitude'],
                'includes' => $tour['includes'],
                'excludes' => $tour['excludes'],
                'itinerary' => $tour['itinerary'],
                'max_participants' => $tour['max_participants'],
                'difficulty_level' => $tour['difficulty_level'],
                'published' => true,
            ]);
        }
    }
}   