<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Tour;
use Illuminate\Support\Str;

class FamilyTourSeeder extends Seeder
{
    public function run()
    {
        $familyTours = [
            [
                'name' => 'Taman Pintar',
                'description' => 'Wahana edukasi interaktif untuk anak-anak dengan berbagai zona pembelajaran sains dan teknologi.',
                'location' => 'Jl. Panembahan Senopati, Kota Yogyakarta',
                'address' => 'Jl. Panembahan Senopati No.1-3, Ngupasan, Gondomanan, Yogyakarta City',
                'latitude' => -7.8014,
                'longitude' => 110.3675,
                'price' => 25000,
                'duration' => '3-4 jam',
                'includes' => 'Tiket masuk semua zona, Parkir, Toilet',
                'excludes' => 'Makanan, Souvenir, Transportasi',
                'itinerary' => 'Pagi: Zona sains dasar. Siang: Zona teknologi dan komputer. Sore: Zona kreativitas dan playground.',
                'max_participants' => 50,
                'difficulty_level' => 'easy',
            ],
            [
                'name' => 'Gembira Loka Zoo',
                'description' => 'Kebun binatang dengan koleksi satwa lengkap dan wahana permainan untuk keluarga.',
                'location' => 'Jl. Kebun Raya, Kota Yogyakarta',
                'address' => 'Jl. Kebun Raya No.2, Rejowinangun, Kotagede, Yogyakarta City',
                'latitude' => -7.8167,
                'longitude' => 110.3833,
                'price' => 35000,
                'duration' => '4-5 jam',
                'includes' => 'Tiket masuk zoo, Parkir, Peta lokasi',
                'excludes' => 'Makanan hewan, Wahana berbayar, Transportasi',
                'itinerary' => 'Pagi: Area mamalia besar. Siang: Area reptil dan burung. Sore: Wahana permainan dan feeding time.',
                'max_participants' => 60,
                'difficulty_level' => 'easy',
            ],
            [
                'name' => 'Sindu Kusuma Edupark (SKE)',
                'description' => 'Taman rekreasi dengan wahana permainan modern dan edukasi. Dilengkapi bianglala dan berbagai rides.',
                'location' => 'Jl. Jambon, Kec. Mlati, Kab. Sleman',
                'address' => 'Jl. Jambon, Sinduharjo, Ngaglik, Sleman Regency',
                'latitude' => -7.7333,
                'longitude' => 110.3667,
                'price' => 50000,
                'duration' => '5-6 jam',
                'includes' => 'Tiket masuk, Parkir, Beberapa wahana gratis',
                'excludes' => 'Wahana berbayar, Makanan, Transportasi',
                'itinerary' => 'Pagi: Wahana anak-anak. Siang: Bianglala dan flying fox. Sore: Area edukasi dan playground.',
                'max_participants' => 40,
                'difficulty_level' => 'easy',
            ],
            [
                'name' => 'Museum Ullen Sentalu',
                'description' => 'Museum budaya Jawa dengan koleksi seni dan sejarah kerajaan. Tur guided yang edukatif untuk keluarga.',
                'location' => 'Kaliurang, Kec. Pakem, Kab. Sleman',
                'address' => 'Jl. Boyong, Kaliurang Barat, Hargobinangun, Pakem, Sleman Regency',
                'latitude' => -7.5833,
                'longitude' => 110.4167,
                'price' => 40000,
                'duration' => '2-3 jam',
                'includes' => 'Tur guided, Brosur museum, Parkir',
                'excludes' => 'Foto di dalam museum, Makanan, Transportasi',
                'itinerary' => 'Pagi: Tur sejarah kerajaan. Siang: Koleksi seni dan budaya. Sore: Taman museum dan souvenir shop.',
                'max_participants' => 25,
                'difficulty_level' => 'easy',
            ],
            [
                'name' => 'De Mata Trick Eye Museum',
                'description' => 'Museum seni 3D interaktif dengan lukisan optical illusion yang sempurna untuk foto keluarga.',
                'location' => 'XT Square, Umbulharjo, Kota Yogyakarta',
                'address' => 'XT Square, Jl. Veteran No.150-151, Pandeyan, Umbulharjo, Yogyakarta City',
                'latitude' => -7.8167,
                'longitude' => 110.3833,
                'price' => 30000,
                'duration' => '2-3 jam',
                'includes' => 'Tiket masuk, Parkir, Tips foto',
                'excludes' => 'Cetak foto, Makanan, Transportasi',
                'itinerary' => 'Pagi: Zona fantasi dan adventure. Siang: Zona horror dan misteri. Sore: Zona klasik dan masterpiece.',
                'max_participants' => 35,
                'difficulty_level' => 'easy',
            ],
            [
                'name' => 'Taman Pelangi Monjali',
                'description' => 'Taman hiburan dengan wahana permainan dan pertunjukan air mancur menari yang spektakuler.',
                'location' => 'Jl. Ring Road Utara, Monjali, Sleman',
                'address' => 'Jl. Ring Road Utara, Karangjati, Sinduharjo, Ngaglik, Sleman Regency',
                'latitude' => -7.7500,
                'longitude' => 110.3667,
                'price' => 45000,
                'duration' => '4-5 jam',
                'includes' => 'Tiket masuk, Parkir, Pertunjukan air mancur',
                'excludes' => 'Wahana berbayar, Makanan, Transportasi',
                'itinerary' => 'Pagi: Wahana anak-anak. Siang: Area playground dan permainan. Malam: Pertunjukan air mancur menari.',
                'max_participants' => 50,
                'difficulty_level' => 'easy',
            ],
            [
                'name' => 'Agrowisata Bhumi Merapi',
                'description' => 'Wisata edukasi pertanian dengan aktivitas memetik buah dan belajar bercocok tanam.',
                'location' => 'Kaliurang, Kec. Pakem, Kab. Sleman',
                'address' => 'Kaliurang, Hargobinangun, Pakem, Sleman Regency',
                'latitude' => -7.5833,
                'longitude' => 110.4000,
                'price' => 35000,
                'duration' => '3-4 jam',
                'includes' => 'Tur kebun, Aktivitas memetik, Guide',
                'excludes' => 'Buah yang dipetik, Makanan, Transportasi',
                'itinerary' => 'Pagi: Tur kebun sayuran. Siang: Memetik buah dan belajar berkebun. Sore: Pengolahan hasil panen.',
                'max_participants' => 30,
                'difficulty_level' => 'easy',
            ],
            [
                'name' => 'The Lost World Castle',
                'description' => 'Kastil bergaya Eropa dengan berbagai spot foto dan wahana permainan untuk keluarga.',
                'location' => 'Dusun Petung, Kepuharjo, Sleman',
                'address' => 'Petung, Kepuharjo, Cangkringan, Sleman Regency',
                'latitude' => -7.5667,
                'longitude' => 110.4333,
                'price' => 40000,
                'duration' => '3-4 jam',
                'includes' => 'Tiket masuk, Parkir, Spot foto',
                'excludes' => 'Makanan, Souvenir, Transportasi',
                'itinerary' => 'Pagi: Eksplorasi kastil. Siang: Foto session di berbagai spot. Sore: Wahana permainan anak.',
                'max_participants' => 40,
                'difficulty_level' => 'easy',
            ],
            [
                'name' => 'Kids Fun Parcs',
                'description' => 'Taman bermain indoor dan outdoor dengan wahana lengkap untuk anak-anak segala usia.',
                'location' => 'Jl. Wonosari KM 10, Piyungan, Kab. Bantul',
                'address' => 'Jl. Wonosari KM 10, Piyungan, Bantul Regency',
                'latitude' => -7.8500,
                'longitude' => 110.4333,
                'price' => 55000,
                'duration' => '4-5 jam',
                'includes' => 'Tiket masuk, Parkir, Beberapa wahana',
                'excludes' => 'Wahana premium, Makanan, Transportasi',
                'itinerary' => 'Pagi: Area playground indoor. Siang: Wahana outdoor dan kolam renang. Sore: Games dan kompetisi.',
                'max_participants' => 45,
                'difficulty_level' => 'easy',
            ],
            [
                'name' => 'HeHa Sky View',
                'description' => 'Destinasi wisata dengan pemandangan alam dan spot foto instagramable di ketinggian.',
                'location' => 'Jl. Dlingo-Patuk, Bukit Patuk, Kab. Gunungkidul',
                'address' => 'Patuk, Gunungkidul Regency',
                'latitude' => -7.8833,
                'longitude' => 110.6000,
                'price' => 45000,
                'duration' => '3-4 jam',
                'includes' => 'Tiket masuk, Parkir, Spot foto',
                'excludes' => 'Makanan, Foto profesional, Transportasi',
                'itinerary' => 'Pagi: Trekking ringan ke viewpoint. Siang: Foto session di sky bridge. Sore: Menikmati pemandangan.',
                'max_participants' => 35,
                'difficulty_level' => 'easy',
            ],
            [
                'name' => 'Jogja Bay Waterpark',
                'description' => 'Waterpark terbesar di Yogyakarta dengan berbagai wahana air untuk semua usia.',
                'location' => 'Maguwoharjo, Sleman',
                'address' => 'Jl. Utara Stadion, Maguwoharjo, Depok, Sleman Regency',
                'latitude' => -7.7500,
                'longitude' => 110.4167,
                'price' => 75000,
                'duration' => '6-8 jam',
                'includes' => 'Tiket masuk, Parkir, Locker, Life jacket',
                'excludes' => 'Makanan, Handuk, Transportasi',
                'itinerary' => 'Pagi: Wahana anak-anak. Siang: Kolam ombak dan lazy river. Sore: Water slide dan area relaksasi.',
                'max_participants' => 60,
                'difficulty_level' => 'easy',
            ],
            [
                'name' => 'Museum De Arca (Patung 3D)',
                'description' => 'Museum patung 3D dengan koleksi seni patung yang dapat disentuh dan difoto.',
                'location' => 'XT Square, Kota Yogyakarta',
                'address' => 'XT Square, Jl. Veteran No.150-151, Pandeyan, Umbulharjo, Yogyakarta City',
                'latitude' => -7.8167,
                'longitude' => 110.3833,
                'price' => 25000,
                'duration' => '2-3 jam',
                'includes' => 'Tiket masuk, Parkir, Guide',
                'excludes' => 'Foto profesional, Makanan, Transportasi',
                'itinerary' => 'Pagi: Zona sejarah dan budaya. Siang: Zona modern dan kontemporer. Sore: Workshop mini sculpting.',
                'max_participants' => 30,
                'difficulty_level' => 'easy',
            ],
            [
                'name' => 'Taman Lampion Kaliurang',
                'description' => 'Taman dengan ribuan lampion warna-warni yang indah di malam hari. Cocok untuk wisata malam keluarga.',
                'location' => 'Kaliurang Barat, Sleman',
                'address' => 'Kaliurang Barat, Hargobinangun, Pakem, Sleman Regency',
                'latitude' => -7.5833,
                'longitude' => 110.4000,
                'price' => 30000,
                'duration' => '2-3 jam (malam)',
                'includes' => 'Tiket masuk, Parkir, Spot foto',
                'excludes' => 'Makanan, Souvenir, Transportasi',
                'itinerary' => 'Sore: Persiapan dan makan malam. Malam: Menikmati lampion dan foto. Malam: Pertunjukan cahaya.',
                'max_participants' => 40,
                'difficulty_level' => 'easy',
            ],
            [
                'name' => 'Desa Wisata Gamplong',
                'description' => 'Wisata edukasi budaya dengan aktivitas membatik, belajar gamelan, dan kuliner tradisional.',
                'location' => 'Moyudan, Sleman',
                'address' => 'Gamplong, Sumberharjo, Prambanan, Sleman Regency',
                'latitude' => -7.7500,
                'longitude' => 110.5000,
                'price' => 40000,
                'duration' => '4-5 jam',
                'includes' => 'Workshop batik, Belajar gamelan, Makan siang tradisional',
                'excludes' => 'Hasil karya batik, Souvenir, Transportasi',
                'itinerary' => 'Pagi: Workshop membatik. Siang: Belajar gamelan dan tari. Sore: Kuliner tradisional dan belanja.',
                'max_participants' => 25,
                'difficulty_level' => 'easy',
            ],
            [
                'name' => 'Obelix Hills',
                'description' => 'Destinasi wisata dengan replika desa Asterix dan Obelix, cocok untuk foto keluarga yang unik.',
                'location' => 'Klumprit, Prambanan, Sleman',
                'address' => 'Klumprit, Bimomartani, Ngemplak, Sleman Regency',
                'latitude' => -7.7333,
                'longitude' => 110.4833,
                'price' => 35000,
                'duration' => '2-3 jam',
                'includes' => 'Tiket masuk, Parkir, Spot foto',
                'excludes' => 'Makanan, Souvenir, Transportasi',
                'itinerary' => 'Pagi: Eksplorasi desa replika. Siang: Foto session dengan kostum. Sore: Area playground dan games.',
                'max_participants' => 35,
                'difficulty_level' => 'easy',
            ],
        ];

        foreach ($familyTours as $tour) {
            Tour::create([
                'name' => $tour['name'],
                'slug' => Str::slug($tour['name']),
                'category' => 'family',
                'description' => $tour['description'],
                'price' => $tour['price'],
                'duration' => $tour['duration'],
                'location' => $tour['location'],
                'address' => $tour['address'],
                'latitude' => $tour['latitude'],
                'longitude' => $tour['longitude'],
                'includes' => $tour['includes'],
                'excludes' => $tour['excludes'],
                'itinerary' => $tour['itinerary'],
                'max_participants' => $tour['max_participants'],
                'difficulty_level' => $tour['difficulty_level'],
                'published' => true,
            ]);
        }
    }
}