<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Tour;
use Illuminate\Support\Str;

class NatureTourSeeder extends Seeder
{
    public function run()
    {
        $natureTours = [
            [
                'name' => 'Pantai Parangtritis',
                'description' => 'Pantai legendaris dengan ombak besar dan pemandangan sunset yang menakjubkan. Terkenal dengan legenda Nyi Roro Kidul dan aktivitas paralayang.',
                'location' => 'Kec. Kretek, Kab. Bantul',
                'address' => 'Parangtritis, Kretek, Bantul Regency, Special Region of Yogyakarta',
                'latitude' => -8.0249,
                'longitude' => 110.3281,
                'price' => 25000,
                'duration' => '4-6 jam',
                'includes' => 'Tiket masuk, Parkir, Guide lokal',
                'excludes' => 'Transportasi, Makan, Aktivitas tambahan',
                'itinerary' => 'Pagi: Perjalanan ke pantai. Siang: Eksplorasi pantai, foto-foto. Sore: Menikmati sunset. Malam: Kembali ke kota.',
                'max_participants' => 50,
                'difficulty_level' => 'easy',
            ],
            [
                'name' => 'Gunung Merapi',
                'description' => 'Gunung berapi aktif yang menawarkan petualangan lava tour dan pemandangan spektakuler. Cocok untuk pecinta alam dan fotografi.',
                'location' => 'Kec. Cangkringan, Kab. Sleman',
                'address' => 'Cangkringan, Sleman Regency, Special Region of Yogyakarta',
                'latitude' => -7.5407,
                'longitude' => 110.4461,
                'price' => 150000,
                'duration' => '1 hari penuh',
                'includes' => 'Jeep 4WD, Guide berpengalaman, Helm safety, Masker debu',
                'excludes' => 'Makan siang, Asuransi perjalanan',
                'itinerary' => 'Pagi: Briefing safety, perjalanan jeep. Siang: Eksplorasi area lava, Museum Sisa Hartaku. Sore: Kembali ke basecamp.',
                'max_participants' => 20,
                'difficulty_level' => 'moderate',
            ],
            [
                'name' => 'Kalibiru',
                'description' => 'Destinasi wisata alam dengan spot foto instagramable di atas pohon pinus. Menawarkan pemandangan Waduk Sermo yang memukau.',
                'location' => 'Kec. Kokap, Kab. Kulon Progo',
                'address' => 'Hargowilis, Kokap, Kulon Progo Regency, Special Region of Yogyakarta',
                'latitude' => -7.8167,
                'longitude' => 110.1167,
                'price' => 35000,
                'duration' => '3-4 jam',
                'includes' => 'Tiket masuk, Spot foto, Parkir',
                'excludes' => 'Transportasi, Makanan, Foto profesional',
                'itinerary' => 'Pagi: Trekking ringan ke spot foto. Siang: Foto session di berbagai spot. Sore: Menikmati pemandangan waduk.',
                'max_participants' => 30,
                'difficulty_level' => 'easy',
            ],
            [
                'name' => 'Hutan Pinus Mangunan',
                'description' => 'Hutan pinus dengan udara sejuk dan spot foto yang instagramable. Cocok untuk camping dan piknik keluarga.',
                'location' => 'Kec. Dlingo, Kab. Bantul',
                'address' => 'Mangunan, Dlingo, Bantul Regency, Special Region of Yogyakarta',
                'latitude' => -7.9167,
                'longitude' => 110.4167,
                'price' => 15000,
                'duration' => '2-3 jam',
                'includes' => 'Tiket masuk, Area parkir, Toilet',
                'excludes' => 'Transportasi, Makanan, Peralatan camping',
                'itinerary' => 'Pagi: Masuk area hutan pinus. Siang: Jelajah hutan, foto-foto. Sore: Piknik atau camping (opsional).',
                'max_participants' => 40,
                'difficulty_level' => 'easy',
            ],
            [
                'name' => 'Air Terjun Sri Gethuk',
                'description' => 'Air terjun alami dengan kolam jernih untuk berenang. Akses dengan perahu tradisional menambah pengalaman unik.',
                'location' => 'Kec. Playen, Kab. Gunungkidul',
                'address' => 'Bleberan, Playen, Gunungkidul Regency, Special Region of Yogyakarta',
                'latitude' => -7.9833,
                'longitude' => 110.7167,
                'price' => 45000,
                'duration' => '4-5 jam',
                'includes' => 'Tiket masuk, Perahu tradisional, Life jacket, Guide lokal',
                'excludes' => 'Transportasi, Makanan, Peralatan renang',
                'itinerary' => 'Pagi: Perjalanan dengan perahu. Siang: Berenang di kolam air terjun. Sore: Eksplorasi sekitar air terjun.',
                'max_participants' => 25,
                'difficulty_level' => 'moderate',
            ],
            [
                'name' => 'Goa Jomblang',
                'description' => 'Gua vertikal dengan cahaya surga yang terkenal. Petualangan caving yang menantang untuk pecinta adrenalin.',
                'location' => 'Kec. Semanu, Kab. Gunungkidul',
                'address' => 'Jetis Wetan, Pacarejo, Semanu, Gunungkidul Regency, Special Region of Yogyakarta',
                'latitude' => -8.0167,
                'longitude' => 110.6833,
                'price' => 200000,
                'duration' => '6-7 jam',
                'includes' => 'Peralatan caving lengkap, Guide profesional, Asuransi, Sertifikat',
                'excludes' => 'Transportasi, Makan siang, Dokumentasi foto',
                'itinerary' => 'Pagi: Briefing safety, persiapan alat. Siang: Turun ke gua, eksplorasi. Sore: Naik kembali, debriefing.',
                'max_participants' => 15,
                'difficulty_level' => 'hard',
            ],
            [
                'name' => 'Bukit Bintang',
                'description' => 'Spot terbaik untuk melihat bintang dan sunrise di Gunungkidul. Cocok untuk camping dan astronomi.',
                'location' => 'Jalan Wonosari KM 15-17, Patuk, Kab. Gunungkidul',
                'address' => 'Patuk, Gunungkidul Regency, Special Region of Yogyakarta',
                'latitude' => -7.8833,
                'longitude' => 110.6167,
                'price' => 20000,
                'duration' => '8-12 jam (camping)',
                'includes' => 'Area camping, Toilet, Tempat parkir',
                'excludes' => 'Peralatan camping, Makanan, Transportasi',
                'itinerary' => 'Sore: Setup camp. Malam: Stargazing. Dini hari: Sunrise viewing. Pagi: Breakdown camp.',
                'max_participants' => 35,
                'difficulty_level' => 'moderate',
            ],
            [
                'name' => 'Pantai Indrayanti',
                'description' => 'Pantai dengan pasir putih dan air laut jernih. Dilengkapi fasilitas lengkap untuk wisata keluarga.',
                'location' => 'Tepus, Kab. Gunungkidul',
                'address' => 'Tepus, Gunungkidul Regency, Special Region of Yogyakarta',
                'latitude' => -8.1500,
                'longitude' => 110.6167,
                'price' => 30000,
                'duration' => '5-6 jam',
                'includes' => 'Tiket masuk, Parkir, Toilet, Tempat bilas',
                'excludes' => 'Transportasi, Makanan, Penyewaan alat pantai',
                'itinerary' => 'Pagi: Perjalanan ke pantai. Siang: Berenang, bermain pasir. Sore: Menikmati sunset, kuliner seafood.',
                'max_participants' => 50,
                'difficulty_level' => 'easy',
            ],
            [
                'name' => 'Tebing Breksi',
                'description' => 'Bekas tambang batu kapur yang disulap menjadi destinasi wisata dengan relief dan spot foto unik.',
                'location' => 'Kec. Prambanan, Kab. Sleman',
                'address' => 'Sambirejo, Prambanan, Sleman Regency, Special Region of Yogyakarta',
                'latitude' => -7.7500,
                'longitude' => 110.4833,
                'price' => 25000,
                'duration' => '2-3 jam',
                'includes' => 'Tiket masuk, Parkir, Guide lokal',
                'excludes' => 'Transportasi, Makanan, Foto profesional',
                'itinerary' => 'Pagi: Eksplorasi tebing dan relief. Siang: Foto session di berbagai spot. Sore: Menikmati pemandangan sekitar.',
                'max_participants' => 40,
                'difficulty_level' => 'easy',
            ],
            [
                'name' => 'Waduk Sermo',
                'description' => 'Waduk buatan dengan pemandangan indah dan aktivitas air. Cocok untuk memancing dan berperahu.',
                'location' => 'Kec. Kokap, Kab. Kulon Progo',
                'address' => 'Kokap, Kulon Progo Regency, Special Region of Yogyakarta',
                'latitude' => -7.8167,
                'longitude' => 110.1000,
                'price' => 15000,
                'duration' => '3-4 jam',
                'includes' => 'Tiket masuk, Area parkir, Toilet',
                'excludes' => 'Sewa perahu, Peralatan memancing, Makanan',
                'itinerary' => 'Pagi: Tiba di waduk. Siang: Aktivitas air atau memancing. Sore: Menikmati pemandangan waduk.',
                'max_participants' => 30,
                'difficulty_level' => 'easy',
            ],
            [
                'name' => 'Lava Tour Merapi',
                'description' => 'Tur khusus melihat sisa-sisa letusan Merapi dengan jeep 4WD. Pengalaman edukatif tentang vulkanologi.',
                'location' => 'Kaliurang, Sleman',
                'address' => 'Kaliurang, Pakem, Sleman Regency, Special Region of Yogyakarta',
                'latitude' => -7.5833,
                'longitude' => 110.4167,
                'price' => 120000,
                'duration' => '4-5 jam',
                'includes' => 'Jeep 4WD, Driver berpengalaman, Helm safety, Guide',
                'excludes' => 'Makan siang, Dokumentasi foto, Asuransi',
                'itinerary' => 'Pagi: Briefing, perjalanan jeep. Siang: Kunjungi Museum Sisa Hartaku, area lava. Sore: Kembali ke basecamp.',
                'max_participants' => 20,
                'difficulty_level' => 'moderate',
            ],
            [
                'name' => 'Pantai Pok Tunggal',
                'description' => 'Pantai tersembunyi dengan pohon duras ikonik. Suasana tenang dan pemandangan laut yang memukau.',
                'location' => 'Tepus, Gunungkidul',
                'address' => 'Tepus, Gunungkidul Regency, Special Region of Yogyakarta',
                'latitude' => -8.1667,
                'longitude' => 110.6000,
                'price' => 25000,
                'duration' => '4-5 jam',
                'includes' => 'Tiket masuk, Parkir, Toilet',
                'excludes' => 'Transportasi, Makanan, Penyewaan alat pantai',
                'itinerary' => 'Pagi: Perjalanan ke pantai. Siang: Berenang, foto dengan pohon duras. Sore: Sunset viewing.',
                'max_participants' => 35,
                'difficulty_level' => 'easy',
            ],
            [
                'name' => 'Gunung Api Purba Nglanggeran',
                'description' => 'Gunung api purba dengan formasi batuan unik. Trekking ringan dengan pemandangan spektakuler.',
                'location' => 'Patuk, Gunungkidul',
                'address' => 'Nglanggeran, Patuk, Gunungkidul Regency, Special Region of Yogyakarta',
                'latitude' => -7.8500,
                'longitude' => 110.6000,
                'price' => 40000,
                'duration' => '4-5 jam',
                'includes' => 'Tiket masuk, Guide lokal, Parkir',
                'excludes' => 'Transportasi, Makanan, Peralatan hiking',
                'itinerary' => 'Pagi: Trekking ke puncak. Siang: Eksplorasi formasi batuan. Sore: Turun gunung, istirahat.',
                'max_participants' => 25,
                'difficulty_level' => 'moderate',
            ],
            [
                'name' => 'Goa Pindul',
                'description' => 'Cave tubing dengan aliran sungai bawah tanah. Petualangan seru dengan pemandangan stalaktit dan stalagmit.',
                'location' => 'Bejiharjo, Karangmojo, Gunungkidul',
                'address' => 'Bejiharjo, Karangmojo, Gunungkidul Regency, Special Region of Yogyakarta',
                'latitude' => -7.9667,
                'longitude' => 110.6833,
                'price' => 75000,
                'duration' => '3-4 jam',
                'includes' => 'Ban pelampung, Life jacket, Helm, Guide berpengalaman',
                'excludes' => 'Transportasi, Makanan, Dokumentasi underwater',
                'itinerary' => 'Pagi: Briefing safety, persiapan alat. Siang: Cave tubing menyusuri goa. Sore: Selesai tur, istirahat.',
                'max_participants' => 20,
                'difficulty_level' => 'moderate',
            ],
            [
                'name' => 'Pantai Wediombo',
                'description' => 'Pantai dengan laguna alami dan kolam renang alam. Cocok untuk berenang dan snorkeling ringan.',
                'location' => 'Girisubo, Gunungkidul',
                'address' => 'Jepitu, Girisubo, Gunungkidul Regency, Special Region of Yogyakarta',
                'latitude' => -8.2000,
                'longitude' => 110.7167,
                'price' => 35000,
                'duration' => '5-6 jam',
                'includes' => 'Tiket masuk, Parkir, Toilet, Tempat bilas',
                'excludes' => 'Transportasi, Makanan, Peralatan snorkeling',
                'itinerary' => 'Pagi: Perjalanan ke pantai. Siang: Berenang di laguna, eksplorasi pantai. Sore: Sunset viewing.',
                'max_participants' => 40,
                'difficulty_level' => 'easy',
            ],
        ];

        foreach ($natureTours as $tour) {
            Tour::create([
                'name' => $tour['name'],
                'slug' => Str::slug($tour['name']),
                'category' => 'nature',
                'description' => $tour['description'],
                'price' => $tour['price'],
                'duration' => $tour['duration'],
                'location' => $tour['location'],
                'address' => $tour['address'],
                'latitude' => $tour['latitude'],
                'longitude' => $tour['longitude'],
                'includes' => $tour['includes'],
                'excludes' => $tour['excludes'],
                'itinerary' => $tour['itinerary'],
                'max_participants' => $tour['max_participants'],
                'difficulty_level' => $tour['difficulty_level'],
                'published' => true,
            ]);
        }
    }
}